name: Build and Release Houdoku

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      bump_version:
        description: "Bump version?"
        type: boolean
        default: false
      version_bump_type:
        description: "Version bump type"
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        if: ${{ inputs.bump_version }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ inputs.version_bump_type }}
          git push --follow-tags

      - id: version
        run: echo "version=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Houdoku v${{ steps.version.outputs.version }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    needs: tag
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_BUILDER_PUBLISH: onTagOrDraft
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dist:win

  macos:
    needs: tag
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_BUILDER_PUBLISH: onTagOrDraft
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dist:mac

  linux:
    needs: tag
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_BUILDER_PUBLISH: onTagOrDraft
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dist:linux
